// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwe77AvQKm_ryLOZOzW1qpeUHWlnPpBWY',
    appId: '1:809631829736:web:94b9f1446c24724310035d',
    messagingSenderId: '809631829736',
    projectId: 'test1-7b3bf',
    authDomain: 'test1-7b3bf.firebaseapp.com',
    storageBucket: 'test1-7b3bf.appspot.com',
    measurementId: 'G-TVT5TJLY6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBteFOxpmTT6jKUQQvvFes-9aU3-nd2X3c',
    appId: '1:809631829736:android:528e6f302dda518210035d',
    messagingSenderId: '809631829736',
    projectId: 'test1-7b3bf',
    storageBucket: 'test1-7b3bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHg0LLamcPeMweSOvvSDXKyo6_TdFk1WE',
    appId: '1:809631829736:ios:9e45441ffebded7310035d',
    messagingSenderId: '809631829736',
    projectId: 'test1-7b3bf',
    storageBucket: 'test1-7b3bf.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHg0LLamcPeMweSOvvSDXKyo6_TdFk1WE',
    appId: '1:809631829736:ios:3875d5c24219280510035d',
    messagingSenderId: '809631829736',
    projectId: 'test1-7b3bf',
    storageBucket: 'test1-7b3bf.appspot.com',
    iosBundleId: 'com.example.test1.RunnerTests',
  );
}
